version: "3.8"
services:
  usuarios-service:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: usuarios-service
    ports:
      - "8080:8080"
    env_file:
      - ../.env.docker
    networks:
      - backend

  prestamos-service:
    build:
      context: ../../prestamos-service
      dockerfile: deployment/Dockerfile
    container_name: prestamos-service
    ports:
      - "8081:8081"
    env_file:
      - ../../prestamos-service/.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
