version: "3.8"

services:
  usuarios-service:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: usuarios-service
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-usuarios
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "8090:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
