server:
  port: 8080

spring:
  application:
    name: "JavaReactivo"
  r2dbc:
    url: r2dbc:postgresql://ep-rough-fire-aecwdwd0-pooler.c-2.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_H6Yrtqn2Shbm
    properties:
      sslMode: require

  sql:
    init:
      platform: postgres

  devtools:
    add-properties: false

  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "*"

# JWT Configuration
jwt:
  secret: "MyVerySecureJwtSecretKeyThatShouldBeChangedInProduction123456789"
  expiration: 86400000 # 24 hours in milliseconds

routes:
  paths:
    register: /api/v1/usuarios
    login: /api/v1/login
    logout: /api/v1/logout
    session: /api/v1/session

adapters:
  restconsumer:
    timeout: 5000
    url: http://localhost:8080
  r2dbc:
    host: ep-rough-fire-aecwdwd0-pooler.c-2.us-east-2.aws.neon.tech
    port: 5432
    database: neondb
    schema: public
    username: neondb_owner
    password: npg_H6Yrtqn2Shbm
    options: sslmode=require

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
microservices:
  solicitud:
    base-url: "http://localhost:8081"
  timeout:
    connection: 5000
    read: 10000
    write: 10000