server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: "JavaReactivo"
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    properties:
      sslMode: require
  sql:
    init:
      platform: postgres

  devtools:
    add-properties: false

  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "*"

# JWT Configuration
jwt:
  secret: "MyVerySecureJwtSecretKeyThatShouldBeChangedInProduction123456789"
  expiration: 86400000 # 24 hours in milliseconds

routes:
  paths:
    register: /api/v1/usuarios
    login: /api/v1/login
    logout: /api/v1/logout
    session: /api/v1/session
    loanApplication: /api/v1/solicitud

adapters:
  restconsumer:
    timeout: 5000
    url: ${REST_CONSUMER_URL}   # ← ahora viene del .env
  r2dbc:
    host: ${R2DBC_HOST}
    port: ${R2DBC_PORT}
    database: ${R2DBC_DATABASE}
    schema: public
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    options: sslmode=require

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

microservices:
  solicitud:
    base-url: ${SOLICITUD_SERVICE_URL}   # ← ahora viene del .env
  timeout:
    connection: 5000
    read: 10000
    write: 10000
